#web:
#  out-path: D:\server
web:
    out-path: /usr/local/server
server:
  port: 80
spring:
  datasource:
    url:
    username:
    password:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      validation-query: SELECT 1
  mvc:
    view:
      prefix: /templates/
      suffix: .html
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 5MB
  resources:
    static-locations: classpath:static/,file:${web.out-path}
  redis:
#    host: 192.168.246.128
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 500
        min-idle: 0
    lettuce:
      shutdown-timeout: 0

mybatis:
  mapper-locations: classpath:/mapper/*Dao.xml
  type-aliases-package: org.eg.confessionwall.entity

